repos:
  - repo: https://github.com/mrsimonemms/pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: license-eye
      - id: go-fmt-import
      - id: go-vet
      - id: gofumpt
      - id: go-err-check
      - id: go-static-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: check-json
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
  - repo: https://github.com/trussworks/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: markdown-toc
        exclude: ^docs
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.9.2
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.54.2
    hooks:
      - id: golangci-lint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        stages:
          - pre-commit
        files: ^docs
  - repo: local
    hooks:
      - id: scan
        name: toodaloo scan
        entry: toodaloo scan --git-files
        language: golang
        args:
          - -s=toodaloo.md
          - -o=markdown
        pass_filenames: false
        exclude: ^docs
